[build]
functions = "functions"

[[redirects]]
  force = true
  from = "/*"
  status = 200
  to = "/.netlify/functions/api"

[[redirects]]
  force = true
  from = "/admin/*"
  status = 200
  to = "/.netlify/functions/api"
[[headers]]
  for = "/admin/*"
  [headers.values]
    Access-Control-Allow-Origin = "https://topcitlcms.netlify.app"