[build]
functions = "functions"
[[redirects]]
  force = true
  from = "/*"
  status = 200
  to = "/.netlify/functions/api/:splat"
[[headers]]
  for = "/admin/:splat"
  [headers.values]
    Access-Control-Allow-Origin = "https://topcitlcms.netlify.app"